- .github/workflows/mirror.yml
Related to:
- #17
This line caused double execution of mirroring job on a PR.
> ci: remove execution of mirroring job on pull request event

- src/utils/log/xmake.lua
I leaved an `add_files` that include cpp files that doesn't exist.
It blocked me while I tried to use Engine² for another plugin
> refactor(Log): remove xmake add_files of cpp where cpp doesn't exist

- src/plugin/physics/src/system/SoftBodyCollision.cpp
- src/plugin/physics/src/system/VelocityIntegration.cpp
Related to:
- #45 
Following #61 we are now able to fix this bug easily.
Although this works perfectly fine, the precision of the simulation could be improved even more by using substeping, but this is for another issue.
> fix: soft body physics breaking at low framerates

- .github/workflows/mirror.yml
- src/plugin/utils/src/HasChanged.hpp
Related to:
- #58 
Use of xmake's official [GitHub Action](https://github.com/xmake-io/github-action-setup-xmake/) for xmake initial setup.
(This PR is not critical)
> ci: use xmake install github action

- src/plugin/object/src/resource/AssetsManager.hpp
- src/plugin/object/tests/AssetsManagerTest.cpp
- src/plugin/ui/xmake.lua
Not linked to any issues.
This modify API of AssetsManager to be more convenient to use with string. It can allow to use hashed string as key and then, know key in all the program even if we don't get it through creation of asset
> feat(AssetsManager): add id key param when adding an asset

- src/plugin/window/src/system/WindowSystem.cpp
- src/plugin/window/src/system/WindowSystem.hpp
Not linked to any issue.
This PR will fix compilation on windows because `CreateWindow` already exist on this OS so we have to rename it.
> [!CAUTION]
> You will need to rename this system in existing projects
> fix(Window): rename CreateWindow system to CreateWindowSystem

- src/engine/src/scheduler/Update.cpp
- src/engine/src/scheduler/Update.hpp
Not related to any issue.
When we want to move a specific object using Update Scheduler, we need (when we want to do it cleanly) to have the delta time since the last update and we currently don't have it so I've added it :)
> feat(Scheduler): add deltatime in update

- src/plugin/physics/src/component/RigidBody3D.hpp
- src/plugin/physics/src/component/SoftBody3D.hpp
When implementing physics in a game, the "JPH::Body" class was a forward declaration which meant that we couldn't use its method externally
This fixes this by including the header in the components that have a JPH::Body
> fix: add missing Body header in physics components

- src/plugin/opengl/src/utils/Loader/Loader.hpp
I'he added a little more infos when having an error while opening a file.
Why not using / having a library to manage files ? It could also be related to @Divengerss tasks which is saving data.
> feat: add string description when having error while opening a file

- src/plugin/opengl/src/system/AllSystems.cpp
When we send color struct to hlsl, we send char sized color channel but hlsl use 0 to 1 value, so we need to "normalize" it.
We should later see if we need to use float instead of char to avoid normalizing colors.
> fix(OpenGL): normalize color for hlsl

- src/engine/src/system/System.hpp
As we start using scenes, we sometimes want to add a new systems in update loop but as we are using `std::vector`, we can't add any systems as `std::vector` is not safe to add / del element while iterating over it
> feat(System): allow adding system in system's loop

- src/engine/src/entity/Entity.hpp
- src/plugin/physics/src/resource/PhysicsManager.hpp
- src/plugin/physics/src/utils/ContactCallback.hpp
- src/plugin/physics/src/utils/ContactListenerImpl.cpp
- src/plugin/physics/src/utils/ContactListenerImpl.hpp
- src/plugin/physics/src/utils/IContactCallback.hpp
In #164 we have discussed the ability to add callbacks only if entities had certain components. This PR implements it
If you want to know how callbacks are handled, I have added documentation in the code. but in short:
- No components: callbacks are always called 
- One component: callbacks are called only if the two entities have the component
- Two component: callbacks are called if entity 1 has the first component and entity 2 has the second component
Notes: 
- when using callbacks with two components needed, the entities will be reordered if needed to match the order of the callback
- the Entity method "HasComponents" is now const (we don't modify the entity so it should be)
Test in RollingBall with something like this:
```cpp
core.RegisterSystem<ES::Engine::Scheduler::Startup>( …
```
> feat(physics): contact callbacks based on entity components

- src/plugin/physics/src/utils/ContactCallback.hpp
- src/plugin/physics/src/utils/IContactCallback.hpp
Kinda dumb to use const references because in most use cases we actually want to modify some components when a collision happens
Previously we had to use the core (because it isn't const) like this:
```cpp
auto &playerComponent = core.GetRegistry().get<Game::Player>(player);
```
Now we can just do this:
```cpp
auto &playerComponent = player.GetComponents<Game::Player>(core);
```
> refactor: remove const from contact callbacks

- src/plugin/window/src/system/WindowSystem.cpp
I fixed the "updated" state of buttons.
Before, `button.pressed` and `pressed` was always the same because we assign each other just before, but it should be done just after.
> fix(OpenGL): make "updated" bool in mouse button works properly

- src/plugin/window/src/resource/Window/Window.hpp
I added a way to toggle fullscreen.
You can find a little demo here:
https://github.com/EngineSquared/Rolling-Ball/pull/16
You just have to click on the middle button (options) and on the square to activate/desactivate fullscreen.
> feat(Window): add toggle for fullscreen

- src/plugin/opengl/src/plugin/PluginOpenGL.cpp
- src/plugin/opengl/src/system/AllSystems.cpp
- src/plugin/opengl/src/system/AllSystems.hpp
This PR add a new callback when resizing the framebuffer (window) that update OpenGL viewport and camera size and aspect ratio.
Example:
> feat(OpenGL): update viewport and camera when resizing

- src/plugin/opengl/src/utils/Texture/Texture.cpp
If you check the ball in the project [Rolling Ball](https://github.com/EngineSquared/Rolling-Ball), texture is not well wrapped around the sphere so I fixed it :)
> fix(OpenGL): use correct format

- src/plugin/opengl/src/system/AllSystems.cpp
- src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.cpp
- src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.hpp
As we have texture on mesh, this PR will allows to put texture on sprites
You can check it [here](https://github.com/EngineSquared/Rolling-Ball). Warning, [this pr](https://github.com/EngineSquared/EngineSquared/pull/188) will fix the ugly pixel displacement :) AND you will also change the color of the button if [this PR](https://github.com/EngineSquared/EngineSquared/pull/187) is not merged
> feat(OpenGL): allow putting texture on sprites

- src/plugin/input/src/resource/InputManager.hpp
- src/plugin/ui/src/system/UpdateButtonState.cpp
- src/plugin/window/src/resource/Window/Window.hpp
Related to:
- #162 
I moved this function into Window class because we want to get the glfw window and it would be not convenient to send core or Window class into the method
> fix: use bottom-left format for return value of GetMousePosition

- src/engine/src/entity/Entity.hpp
- src/utils/log/src/EntityToIDString.hpp
- src/utils/log/xmake.lua
Related to:
- #204 
Entities IDs are now displayed with their index and version. If an entity index is reused but the entity has a different version, it will be shown on logs. This was made to reduce clutter in logs
On this example: the entity at index 0 was destroyed and then reused
> feat(log): display entity ids with index and version

- src/plugin/sound/xmake.lua
Not related to any issue
The engine won't compile due to missing `fmt` dependency in the sound plugin xmake
> fix(Sound): missing fmt dependency in xmake

- src/plugin/opengl/src/system/RenderSystems.cpp
Related to:
- #160 
`MaterialHandle`, `ModelHandle` and `TextureHandle` cannot provide default values yet, thus, I didn't modify the code for them.
P.S: `MaterialHandle` could provide a placeholder texture by default, but this should be done in another issue.
> refactor(OpenGL): assigning default handles if not provided upon entities creation

- src/plugin/camera/xmake.lua
- src/plugin/colors/xmake.lua
- src/plugin/utils/xmake.lua
- src/utils/function-container/xmake.lua
- src/utils/log/xmake.lua
- xmake.lua
As we are only using header file inside `Camera`, `Colors`, `Utils` plugins and `FunctionContainer`, `FunctionContainer` utils, I've defined the kind of Xmake target as header file only. And, as root Xmake only collect some other targets, I've made it a "Object".
> build: set headeronly and object for proper xmake

- src/plugin/physics/src/utils/WheeledVehicleBuilder.hpp
- src/plugin/physics/src/utils/WheeledVehicleBuilder.inl
Not related to any issues
Vehicle wheels were wrongly set to initial position, they should be attached by Jolt anyways
I have also added utility functions with the builder to change each wheel individually
> fix: bad vehicle wheel offset and position

- .github/workflows/ci.yml
- src/engine/src/scheduler/FixedTimeUpdate.cpp
Not related to any issues
Allow the linter to work again following PR #254 
Note:
- We are a public repository, so the GitHub Action bot doesn't need an SSH key or a PAT at all
> ci: fix ci linter

- src/plugin/opengl/src/utils/Viewer.cpp
- src/plugin/opengl/src/utils/Viewer.hpp
Not related to any issue.
The OpenGL Viewer class doesn't provide any getter for the camera rotation, nor a simple way to rotate it based on a source rotation. I added both functions to easily set it from a target.
A usage example can be found here:
- [ES-RS](https://github.com/EngineSquared/ES-RS/pull/4)
> feat(OpenGL): handling camera rotation from a source target

- src/plugin/ui/src/resource/UIResource.cpp
- src/plugin/ui/src/resource/UIResource.hpp
- src/plugin/ui/src/system/InitUI.cpp
- src/plugin/ui/src/utils/EventListener.cpp
- src/plugin/ui/src/utils/EventListener.hpp
Not related to any issue:
The current implementation of the Event Handlers of Rmlui doesn't allow the usage of multiple callbacks per document. This PR provides a fix for it, so multiple callbacks can be assigned to different UI elements.
> fix(UI): allowing assignment of multiple event listeners per document

- src/plugin/object/src/resource/OBJLoader.cpp
- src/plugin/object/src/resource/OBJLoader.hpp
- src/plugin/object/src/utils/Shape.hpp
Related to no issues.
Introduces a new Shape struct to encapsulate mesh data and extends OBJLoader with a new loadModel overload that loads OBJ files into a vector of Shape objects. This enables more flexible handling of complex OBJ files with multiple shapes.
> feat(object): add Shape struct and OBJLoader support for shapes

- src/engine/src/plugin/IPlugin.hpp
- src/plugin/opengl/src/utils/Loader.hpp
- src/plugin/physics/src/utils/ContactListenerImpl.hpp
Related to no issue.
When compiling on MacOS, I have some warnings which I fixed in this PR. I know that MacOS isn't officially in our supported platforms but it's also generally more clean.
> refactor: remove some warnings

- src/plugin/sound/src/resource/SoundManager.hpp
Not related to any issue.
The SoundPlugin is able to play sounds without specifying any loop. The sound will play once but won't be able to play again unless stopped intentionally by the user. This PR provides a fix by setting back the PCM frame to the beginning after the sound has been played entirely.
> fix(Sound): pcm frame reset for non-looping sounds
